In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 100)

In [4]:
survey = pd.read_csv("with_features.csv")

In [20]:
survey.head(2)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat,num_languages,num_databases,num_platforms,num_frameworks,experience_group,salary_bucket,has_degree,log_salary,remote,is_fulltime,ai_usage_score,seniority,is_manager,tech_diversity,db_specialist,polyglot,web_developer,PrimaryRole
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0,3,2,5,0,Senior,Medium,1,11.022833,remote,0,NaN,Developer,0,10,0,0,0,"developer, mobile"
1,2,i am a developer by profession,25-34 years old,"associate degree (a.a., a.s., etc.)",employed,NaN,2.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,10.0,"developer, back-end",500 to 999 employees,individual contributor,"hybrid (some in-person, leans heavy to flexibility)",no,personal project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,retail and consumer services,10.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,i'm not sure,i have transitioned into a new career and/or industry voluntarily,6.0,5.0,netherlands,eur european euro,90000.0,yes,java,java;python;swift,java,yes,dynamodb;mongodb,dynamodb;mongodb,dynamodb;mongodb,yes,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,yes,spring boot,spring boot,spring boot,yes,intellij idea;pycharm;visual studio code;xcode,intellij idea;pycharm;visual studio code;xcode,intellij idea;pycharm;visual studio code;xcode,NaN,NaN,NaN,windows;macos;ios;ipados,macos,confluence;github;jira,confluence;github;jira,confluence;github;jira,"stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...","stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...","stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...",yes,openai gpt (chatbot models),openai gpt (chatbot models),openai gpt (chatbot models),not sure/can't remember,multiple times per day,between 10 and 15 years,"infrequently, less than once per year",chat (people);message boards;long-form articles;videos;coding challenges;logic games/puzzles;lis...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,"yes, somewhat",about half of the time,"yes, i use ai tools weekly",indifferent,neither trust nor distrust,bad at handling complex tasks,learning new concepts or technologies,learning about a codebase;project planning;committing and reviewing code;deployment and monitoring,writing code;documenting code;debugging or fixing code;testing code;predictive analytics;search ...,NaN,NaN,"ai solutions that are almost right, but not quite;debugging ai-generated code is more time-consu...",no,"no, and i don't plan to",not at all or minimally,NaN,NaN,it takes significant time and effort to learn how to use ai agents effectively.;the cost of usin...,NaN,i am concerned about the accuracy of the information provided by ai agents.;i have concerns abou...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,when i don’t trust ai’s answers;when i want to fully understand something;when i want to learn b...,all skills. ai is a flop.,104413.0,9.0,1,2,7,1,Mid,High,0,11.556119,"hybrid (some in-person, leans heavy to flexibility)",0,NaN,Developer,0,11,0,0,0,"developer, back-end"

## Advanced Recommendation System

In [5]:
survey["PrimaryRole"] = (
    survey["DevType"]
    .str.split(";")
    .str[0]
)

In [6]:
survey = survey[survey["YearsCode"] <= 40]

In [31]:
survey.shape

(47372, 152)

In [7]:
# Convert unknown values to NaN
survey["WorkExp"] = survey["WorkExp"].replace(
    r"(?i)^unknown$",
    np.nan,
    regex=True
)

# Convert to numeric
survey["WorkExp"] = pd.to_numeric(
    survey["WorkExp"],
    errors="coerce"
)

# Calculate median
median_workexp = survey["WorkExp"].median()

# Fill missing values with median
survey["WorkExp"] = survey["WorkExp"].fillna(median_workexp)

In [8]:
survey = survey[survey["WorkExp"] <= 50]

In [10]:
survey.shape

(47339, 152)

In [9]:
def education_group(x):
    if pd.isna(x):
        return "Unknown"
    
    x = str(x).lower()
    
    if "doctoral" in x or "ph.d" in x:
        return "Doctorate"
    
    elif "master" in x:
        return "Master"
    
    elif "bachelor" in x:
        return "Bachelor"
    
    elif "associate" in x:
        return "Associate"
    
    elif "professional" in x:
        return "Professional"
    
    elif "secondary" in x or "high school" in x:
        return "Secondary"
    
    else:
        return "Other"

In [10]:
survey["EducationGroup"] = survey["EdLevel"].apply(education_group)

In [61]:
survey['OrgSize'].value_counts()

OrgSize
unknown                                               14322
20 to 99 employees                                     6526
100 to 499 employees                                   5927
less than 20 employees                                 5422
10,000 or more employees                               4754
1,000 to 4,999 employees                               4020
500 to 999 employees                                   2282
just me - i am a freelancer, sole proprietor, etc.     1632
5,000 to 9,999 employees                               1534
i don’t know                                            920
Name: count, dtype: int64

In [11]:
org_mapping = {
    "Just me - I am a freelancer, sole proprietor, etc.": 0,
    "less than 20 employees": 1,
    "20 to 99 employees": 2,
    "100 to 499 employees": 3,
    "500 to 999 employees": 4,
    "1,000 to 4,999 employees": 5,
    "5,000 to 9,999 employees": 6,
    "10,000 or more employees": 7,
    "Unknown": 3,
    "i don't know": 3
}

survey["OrgSizeScore"] = survey["OrgSize"].map(org_mapping)

In [12]:
survey['Employment'].value_counts()

Employment
employed                                                32761
independent contractor, freelancer, or self-employed     6285
student                                                  4403
not employed                                             2161
unknown                                                  1345
retired                                                   384
Name: count, dtype: int64

In [26]:
survey.head(1)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat,num_languages,num_databases,num_platforms,num_frameworks,experience_group,salary_bucket,has_degree,log_salary,remote,is_fulltime,ai_usage_score,seniority,is_manager,tech_diversity,db_specialist,polyglot,web_developer,PrimaryRole,EducationGroup,OrgSizeScore
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0,3,2,5,0,Senior,Medium,1,11.022833,remote,0,NaN,Developer,0,10,0,0,0,"developer, mobile",Master,2.0

In [31]:
survey['AISelect'].unique()

array(['yes, i use ai tools monthly or infrequently',
       'yes, i use ai tools weekly', 'yes, i use ai tools daily',
       "no, and i don't plan to", 'unknown', 'no, but i plan to soon'],
      dtype=object)

In [12]:
mapping = {
    "no, and i don't plan to":0,
    "no, but i plan to soon":1,
    "yes, i use ai tools monthly or infrequently":2,
    "yes, i use ai tools weekly":3,
    "yes, i use ai tools daily":4,
    "Unknown":2
}

survey["ai_usage_score"] = survey["AISelect"].map(mapping)

In [13]:
profile_features = [
    
    "PrimaryRole",
    "YearsCode",
    "WorkExp",
    "experience_group",
    "seniority",
    "EducationGroup",
    "OrgSizeScore",
    "Employment",
    "ai_usage_score"
]

developer_profile = survey[profile_features].copy()

In [34]:
developer_profile.head()

            PrimaryRole  YearsCode  WorkExp experience_group  seniority EducationGroup  OrgSizeScore                                            Employment  ai_usage_score
0     developer, mobile       14.0      8.0           Senior  Developer         Master           2.0                                              employed             2.0
1   developer, back-end       10.0      2.0              Mid  Developer      Associate           4.0                                              employed             3.0
2  developer, front-end       12.0     10.0           Senior  Developer       Bachelor           NaN  independent contractor, freelancer, or self-employed             4.0
3   developer, back-end        5.0      4.0           Junior  Developer       Bachelor           7.0                                              employed             3.0
4   engineering manager       22.0     21.0           Expert    Manager         Master           NaN  independent contractor, freelancer, or self-employed             3.0

In [14]:
survey["LearnCode"] = survey["LearnCode"].fillna(
    survey["LearnCode"].mode()
)

In [15]:
developer_profile['OrgSizeScore'] = developer_profile['OrgSizeScore'].fillna(developer_profile['OrgSizeScore'].median())

In [35]:
developer_profile.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47339 entries, 0 to 49122
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PrimaryRole       47339 non-null  object
 1   YearsCode         47339 non-null  float64
 2   WorkExp           47339 non-null  float64
 3   experience_group  47339 non-null  object
 4   seniority         47339 non-null  object
 5   EducationGroup    47339 non-null  object
 6   OrgSizeScore      30465 non-null  float64
 7   Employment        47339 non-null  object
 8   ai_usage_score    32190 non-null  float64
dtypes: float64(4), object(5)
memory usage: 3.6+ MB

In [37]:
developer_profile.isna().sum()

PrimaryRole             0
YearsCode               0
WorkExp                 0
experience_group        0
seniority               0
EducationGroup          0
OrgSizeScore        16874
Employment              0
ai_usage_score      15149
dtype: int64

In [16]:
categorical_features = [
    "PrimaryRole",
    "experience_group",
    "seniority",
    "EducationGroup",
    "Employment"
]

numerical_features = [
    "YearsCode",
    "WorkExp",
    "OrgSizeScore",
    "ai_usage_score"
]

In [17]:
for col in numerical_features:
    developer_profile[col] = (
        developer_profile[col]
        .fillna(developer_profile[col].median())
    )

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [20]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['YearsCode', 'WorkExp', 'OrgSizeScore',
                                  'ai_usage_score']),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['PrimaryRole', 'experience_group',
                                  'seniority', 'EducationGroup',
                                  'Employment'])])

In [21]:
X_profile = preprocessor.fit_transform(
    developer_profile[
        categorical_features + numerical_features
    ]
)

In [23]:
profile_feature_names = (
    preprocessor
    .get_feature_names_out()
)

In [25]:
print(
    "Number of profile features:",
    len(profile_feature_names)
)

Number of profile features: 58

In [26]:
print(
    "Matrix columns:",
    X_profile.shape[1]
)

Matrix columns: 58

In [27]:
developer_profile = developer_profile.reset_index(drop=True)

developer_profile["DeveloperID"] = developer_profile.index

In [28]:
print("Developers:", X_profile.shape[0])
print("Profile features:", X_profile.shape[1])
print("Feature names:", len(profile_feature_names))

Developers: 47339
Profile features: 58
Feature names: 58