In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 100)

In [2]:
survey = pd.read_csv("with_features.csv")

In [5]:
survey.head(1)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat,num_languages,num_databases,num_platforms,num_frameworks,experience_group,salary_bucket,has_degree,log_salary,remote,is_fulltime,ai_usage_score,seniority,is_manager,tech_diversity,db_specialist,polyglot,web_developer,PrimaryRole,EducationGroup,OrgSizeScore
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0,3,2,5,0,Senior,Medium,1,11.022833,remote,0,2.0,Developer,0,10,0,0,0,"developer, mobile",Master,2.0

In [16]:
tech = survey[['ResponseId','LanguageHaveWorkedWith']]

In [20]:
tech = (
    survey["LanguageHaveWorkedWith"]
    .fillna("")
    .str.get_dummies(sep=";")
)

In [19]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [23]:
frequent_itemsets = apriori(
    tech,
    min_support=0.02,
    use_colnames=True
)

frequent_itemsets.head()

d:\Anaconda\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support                   itemsets
0  0.044361                 (assembly)
1  0.311160  (bash/shell (all shells))
2  0.138131                        (c)
3  0.177570                       (c#)
4  0.149116                      (c++)

In [25]:
frequent_itemsets.head()

    support                   itemsets
0  0.044361                 (assembly)
1  0.311160  (bash/shell (all shells))
2  0.138131                        (c)
3  0.177570                       (c#)
4  0.149116                      (c++)

In [26]:
rules = association_rules(
    frequent_itemsets,
    metric="lift",
    min_threshold=1
)

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(bash/shell (all shells)),(assembly),0.311160,0.044361,0.033947,0.109097,2.459308,1.0,0.020143,1.072664,0.861421,0.105564,0.067741,0.437168
1,(assembly),(bash/shell (all shells)),0.044361,0.311160,0.033947,0.765238,2.459308,1.0,0.020143,2.934207,0.620926,0.105564,0.659192,0.437168
2,(assembly),(c),0.044361,0.138131,0.036291,0.818095,5.922589,1.0,0.030164,4.738021,0.869737,0.248230,0.788941,0.540413
3,(c),(assembly),0.138131,0.044361,0.036291,0.262731,5.922589,1.0,0.030164,1.296188,0.964364,0.248230,0.228507,0.540413
4,(assembly),(c++),0.044361,0.149116,0.029785,0.671429,4.502728,1.0,0.023170,2.589647,0.814023,0.181959,0.613847,0.435587

In [27]:
rules.sort_values(
    "lift",
    ascending=False
).head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
2395,"(html/css, c)","(assembly, javascript)",0.084603,0.028306,0.020026,0.236704,8.362191,1.0,0.017631,1.273023,0.961783,0.215602,0.214468,0.472083
2398,"(assembly, javascript)","(html/css, c)",0.028306,0.084603,0.020026,0.707463,8.362191,1.0,0.017631,3.129165,0.906062,0.215602,0.680426,0.472083
2399,"(c, javascript)","(html/css, assembly)",0.086525,0.028412,0.020026,0.231445,8.146015,1.0,0.017567,1.264175,0.960333,0.210995,0.208971,0.468139
2394,"(html/css, assembly)","(c, javascript)",0.028412,0.086525,0.020026,0.704833,8.146015,1.0,0.017567,3.094771,0.902894,0.210995,0.676874,0.468139
20062,"(sql, javascript, c++)","(html/css, c, typescript)",0.059528,0.042481,0.020596,0.345990,8.144616,1.0,0.018067,1.464074,0.932744,0.252984,0.316975,0.415412
20051,"(html/css, c, typescript)","(sql, javascript, c++)",0.042481,0.059528,0.020596,0.484833,8.144616,1.0,0.018067,1.825569,0.916138,0.252984,0.452225,0.415412
21308,"(python, sql, c, javascript)","(html/css, bash/shell (all shells), c++)",0.047107,0.055303,0.021166,0.449327,8.124793,1.0,0.018561,1.715532,0.920271,0.260530,0.417091,0.416031
21349,"(html/css, bash/shell (all shells), c++)","(python, sql, c, javascript)",0.055303,0.047107,0.021166,0.382735,8.124793,1.0,0.018561,1.543734,0.928255,0.260530,0.352220,0.416031
2322,"(bash/shell (all shells), c, c++)",(assembly),0.059084,0.044361,0.021209,0.358956,8.091723,1.0,0.018588,1.490754,0.931451,0.257899,0.329199,0.418526
2331,(assembly),"(bash/shell (all shells), c, c++)",0.044361,0.059084,0.021209,0.478095,8.091723,1.0,0.018588,1.802849,0.917100,0.257899,0.445322,0.418526
21311,"(html/css, sql, c, python)","(bash/shell (all shells), javascript, c++)",0.046621,0.056212,0.021166,0.454010,8.076805,1.0,0.018546,1.728582,0.919035,0.259183,0.421491,0.415280
21346,"(bash/shell (all shells), javascript, c++)","(html/css, sql, c, python)",0.056212,0.046621,0.021166,0.376550,8.076805,1.0,0.018546,1.529199,0.928374,0.259183,0.346063,0.415280
21340,"(html/css, python, c)","(bash/shell (all shells), sql, javascript, c++)",0.068274,0.038594,0.021166,0.310025,8.032984,1.0,0.018532,1.393392,0.939668,0.246981,0.282327,0.429232
21317,"(bash/shell (all shells), sql, javascript, c++)","(html/css, python, c)",0.038594,0.068274,0.021166,0.548440,8.032984,1.0,0.018532,2.063351,0.910659,0.246981,0.515351,0.429232
2328,"(assembly, c++)","(bash/shell (all shells), c)",0.029785,0.088743,0.021209,0.712057,8.023817,1.0,0.018566,3.164711,0.902245,0.217929,0.684015,0.475524
2325,"(bash/shell (all shells), c)","(assembly, c++)",0.088743,0.029785,0.021209,0.238991,8.023817,1.0,0.018566,1.274905,0.960619,0.217929,0.215628,0.475524
20064,"(html/css, c++, typescript)","(sql, c, javascript)",0.045269,0.056740,0.020596,0.454970,8.018544,1.0,0.018028,1.730657,0.916792,0.252984,0.422185,0.408981
20049,"(sql, c, javascript)","(html/css, c++, typescript)",0.056740,0.045269,0.020596,0.362993,8.018544,1.0,0.018028,1.498777,0.927940,0.252984,0.332789,0.408981
19864,"(python, c, javascript)","(html/css, java, c++)",0.069794,0.039777,0.022096,0.316586,7.959035,1.0,0.019320,1.405039,0.939961,0.252596,0.288276,0.436041
19877,"(html/css, java, c++)","(python, c, javascript)",0.039777,0.069794,0.022096,0.555497,7.959035,1.0,0.019320,2.092685,0.910577,0.252596,0.522145,0.436041

In [28]:
strong_rules = rules[
    (rules["confidence"] > 0.6) &
    (rules["lift"] > 1.5)
]

strong_rules.sort_values(
    "lift",
    ascending=False
)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
2398,"(assembly, javascript)","(html/css, c)",0.028306,0.084603,0.020026,0.707463,8.362191,1.0,0.017631,3.129165,0.906062,0.215602,0.680426,0.472083
2394,"(html/css, assembly)","(c, javascript)",0.028412,0.086525,0.020026,0.704833,8.146015,1.0,0.017567,3.094771,0.902894,0.210995,0.676874,0.468139
2328,"(assembly, c++)","(bash/shell (all shells), c)",0.029785,0.088743,0.021209,0.712057,8.023817,1.0,0.018566,3.164711,0.902245,0.217929,0.684015,0.475524
2342,"(assembly, python)","(bash/shell (all shells), c)",0.034665,0.088743,0.023955,0.691042,7.787012,1.0,0.020879,2.949453,0.902879,0.240867,0.660954,0.480489
12389,"(html/css, c, c#)","(javascript, c++)",0.029109,0.091109,0.020533,0.705370,7.742062,1.0,0.017881,3.084857,0.896945,0.205976,0.675836,0.465368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,"(python, c++)",(html/css),0.113268,0.399776,0.069647,0.614883,1.538067,1.0,0.024365,1.558548,0.394520,0.157075,0.358377,0.394548
503,"(bash/shell (all shells), c++)",(javascript),0.085722,0.426688,0.056212,0.655742,1.536817,1.0,0.019635,1.665353,0.382055,0.123217,0.399527,0.393740
1060,"(python, c)",(javascript),0.106529,0.426688,0.069794,0.655166,1.535466,1.0,0.024340,1.662571,0.390312,0.150606,0.398522,0.409369
55,(c),(html/css),0.138131,0.399776,0.084603,0.612479,1.532055,1.0,0.029381,1.548881,0.402941,0.186635,0.354373,0.412052
906,"(c, c++)",(html/css),0.091341,0.399776,0.055514,0.607771,1.520277,1.0,0.018998,1.530288,0.376627,0.127443,0.346528,0.373317